DEBUG    urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): mytest.ytoglobal.com:8080
DEBUG    urllib3.connectionpool:connectionpool.py:452 https://mytest.ytoglobal.com:8080 "POST /gateway/app/user/login HTTP/1.1" 502 166
ERROR    root:logs.py:37 登录报错Expecting value: line 1 column 1 (char 0)