{"name": "test_user_list", "status": "broken", "statusDetails": {"message": "pymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1\")", "trace": "self = <class 'test_set.TestUser'>\n\n    def teardown_class(self):\n        userId = self.sql_exec.select_all(self.sql['user']['id'])\n    \n        userId_list = []\n        for i in userId:\n            for j in i:\n                userId_list.append(j)\n        userId_tuple = tuple(userId_list)\n        userId_tuple = userId_tuple + ('sue',)\n    \n        self.sql_exec.update(self.sql['user']['clear_user'])\n>       self.sql_exec.update(self.sql['user']['clear_relate'].format(userId_tuple))\n\ntestcase\\test_set.py:293: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ncommon\\execSql.py:63: in update\n    self.cur.execute(sql)\nvenv\\lib\\site-packages\\pymysql\\cursors.py:148: in execute\n    result = self._query(query)\nvenv\\lib\\site-packages\\pymysql\\cursors.py:310: in _query\n    conn.query(q)\nvenv\\lib\\site-packages\\pymysql\\connections.py:548: in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\nvenv\\lib\\site-packages\\pymysql\\connections.py:775: in _read_query_result\n    result.read()\nvenv\\lib\\site-packages\\pymysql\\connections.py:1156: in read\n    first_packet = self.connection._read_packet()\nvenv\\lib\\site-packages\\pymysql\\connections.py:725: in _read_packet\n    packet.raise_for_error()\nvenv\\lib\\site-packages\\pymysql\\protocol.py:221: in raise_for_error\n    err.raise_mysql_exception(self._data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndata = b\"\\xff(\\x04#42000You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1\"\n\n    def raise_mysql_exception(data):\n        errno = struct.unpack(\"<h\", data[1:3])[0]\n        errval = data[9:].decode(\"utf-8\", \"replace\")\n        errorclass = error_map.get(errno)\n        if errorclass is None:\n            errorclass = InternalError if errno < 1000 else OperationalError\n>       raise errorclass(errno, errval)\nE       pymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1\")\n\nvenv\\lib\\site-packages\\pymysql\\err.py:143: ProgrammingError"}, "start": 1627893554260, "stop": 1627893554260, "uuid": "435e03fb-d2f7-4129-bbfd-6a9d00aeb898", "historyId": "3ce6a0761b83ef8633eff7623791a978", "testCaseId": "b625e37d040d10c4ae577bb256d4c6dc", "fullName": "testcase.test_set.TestUser#test_user_list", "labels": [{"name": "feature", "value": "用户管理"}, {"name": "story", "value": "用户信息查询接口"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_set"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "DESKTOP-M0PGOTF"}, {"name": "thread", "value": "9928-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_set"}]}