{"status": "broken", "uuid": "023a0f41-879b-4dda-8419-9d8691f20690", "labels": [{"name": "story", "value": "查看个人信息接口"}, {"name": "feature", "value": "个人信息"}, {"name": "tag", "value": "@pytest.mark.usefixtures('userId')"}, {"name": "suite", "value": "test_set"}, {"name": "subSuite", "value": "TestPerson"}, {"name": "parentSuite", "value": "testcase"}, {"name": "host", "value": "DESKTOP-M0PGOTF"}, {"name": "thread", "value": "13804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "testcase.test_set"}], "stop": 1629252153746, "testCaseId": "9c2e15463fbb8b8b68f613b930a75f04", "historyId": "8c0f104f87c8845eb4e63676f6f01dbd", "start": 1629252153746, "fullName": "testcase.test_set.TestPerson#test_person_info", "statusDetails": {"message": "TypeError: 'NoneType' object has no attribute '__getitem__'", "trace": "@pytest.fixture(scope='session')\n    def userId():\n>       userId = Login().yt_login('易通')['data']['userId']\nE       TypeError: 'NoneType' object has no attribute '__getitem__'\n\ntestcase\\conftest.py:23: TypeError"}, "name": "test_person_info"}