{"status": "broken", "uuid": "1245e4fd-06ed-47e9-9c7b-9b3710b5a181", "labels": [{"name": "feature", "value": "用户管理"}, {"name": "story", "value": "查看下级账号"}, {"name": "tag", "value": "@pytest.mark.usefixtures('userId')"}, {"name": "suite", "value": "test_set"}, {"name": "subSuite", "value": "TestUser"}, {"name": "parentSuite", "value": "testcase"}, {"name": "host", "value": "DESKTOP-M0PGOTF"}, {"name": "thread", "value": "13804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "testcase.test_set"}], "stop": 1629252153736, "testCaseId": "81455f4e47b03495f45298dff6a0c9bf", "historyId": "52e13c83e60ea6cd2e56e74419e01d97", "start": 1629252153736, "fullName": "testcase.test_set.TestUser#test_subuser", "statusDetails": {"message": "TypeError: 'NoneType' object has no attribute '__getitem__'", "trace": "@pytest.fixture(scope='session')\n    def userId():\n>       userId = Login().yt_login('易通')['data']['userId']\nE       TypeError: 'NoneType' object has no attribute '__getitem__'\n\ntestcase\\conftest.py:23: TypeError"}, "name": "test_subuser"}