{"status": "broken", "uuid": "b89b32ea-afd1-4d28-b359-f69a2ec94167", "labels": [{"name": "story", "value": "启用禁用下级账号"}, {"name": "feature", "value": "用户管理"}, {"name": "tag", "value": "@pytest.mark.usefixtures('userId')"}, {"name": "suite", "value": "test_set"}, {"name": "subSuite", "value": "TestUser"}, {"name": "parentSuite", "value": "testcase"}, {"name": "host", "value": "DESKTOP-M0PGOTF"}, {"name": "thread", "value": "13804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "testcase.test_set"}], "stop": 1629252153730, "testCaseId": "7331d9f0e682852cb7028c9f0ae5f614", "historyId": "60c415f794bc065b623bd5e3b1f3b5c7", "start": 1629252153730, "fullName": "testcase.test_set.TestUser#test_user_status", "statusDetails": {"message": "TypeError: 'NoneType' object has no attribute '__getitem__'", "trace": "@pytest.fixture(scope='session')\n    def userId():\n>       userId = Login().yt_login('易通')['data']['userId']\nE       TypeError: 'NoneType' object has no attribute '__getitem__'\n\ntestcase\\conftest.py:23: TypeError"}, "name": "test_user_status"}