{"status": "broken", "uuid": "9120d34a-36d8-4494-b74b-3c2b9cd39a04", "labels": [{"name": "story", "value": "修改用户信息接口"}, {"name": "feature", "value": "用户管理"}, {"name": "tag", "value": "@pytest.mark.usefixtures('userId')"}, {"name": "suite", "value": "test_set"}, {"name": "subSuite", "value": "TestUser"}, {"name": "parentSuite", "value": "testcase"}, {"name": "host", "value": "DESKTOP-M0PGOTF"}, {"name": "thread", "value": "13804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "testcase.test_set"}], "stop": 1629252153725, "testCaseId": "f745953229fb37c691dd34a4c980d529", "historyId": "8da4f6b101e9943164247867fee46015", "start": 1629252153725, "fullName": "testcase.test_set.TestUser#test_user_update", "statusDetails": {"message": "TypeError: 'NoneType' object has no attribute '__getitem__'", "trace": "@pytest.fixture(scope='session')\n    def userId():\n>       userId = Login().yt_login('易通')['data']['userId']\nE       TypeError: 'NoneType' object has no attribute '__getitem__'\n\ntestcase\\conftest.py:23: TypeError"}, "name": "test_user_update"}