{"status": "broken", "uuid": "f2060a7d-9981-429e-b464-6ce391560d19", "labels": [{"name": "story", "value": "角色授权接口"}, {"name": "feature", "value": "角色管理"}, {"name": "tag", "value": "@pytest.mark.usefixtures('userId')"}, {"name": "suite", "value": "test_set"}, {"name": "subSuite", "value": "TestRole"}, {"name": "parentSuite", "value": "testcase"}, {"name": "host", "value": "DESKTOP-M0PGOTF"}, {"name": "thread", "value": "13804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "testcase.test_set"}], "stop": 1629252153698, "testCaseId": "d996f3ba21327fe14dadac45cc4bfc54", "historyId": "402493687cf03b2b0e30e29210f9f152", "start": 1629252153698, "fullName": "testcase.test_set.TestRole#test_role_auth", "statusDetails": {"message": "TypeError: 'NoneType' object has no attribute '__getitem__'", "trace": "@pytest.fixture(scope='session')\n    def userId():\n>       userId = Login().yt_login('易通')['data']['userId']\nE       TypeError: 'NoneType' object has no attribute '__getitem__'\n\ntestcase\\conftest.py:23: TypeError"}, "name": "test_role_auth"}